name: Shopify Theme Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Verify token
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: |
          if [ -z "$SHOPIFY_CLI_AUTH_TOKEN" ]; then
            echo "❌ TOKEN MISSING"
            exit 1
          else
            echo "✅ TOKEN FOUND"
          fi

      - name: Push theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: |
          shopify theme push \
            --store jwala-test.myshopify.com \
            --path .